version: '3'

services:
  nginx:
    build:
      context: .
    image: admin-ui
    container_name: admin-ui
    ports:
      - 8080:80
    environment:
      - NGINX_HOST
      - NGINX_PORT
      - API_HOST
      - API_PORT